# Generated by Django 5.1 on 2024-12-28 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oharaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokuten_post',
            name='num',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='点数'),
        ),
    ]
